name: medwaster

services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: medwaster-postgres
    environment:
      POSTGRES_DB: medwaster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - medwaster_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio
    networks:
      - medwaster-network
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - medwaster_minio_data:/data
    restart: unless-stopped

volumes:
  medwaster_postgres_data:
  medwaster_minio_data:

networks:
  medwaster-network:
    driver: bridge
